---
#        - hosts: all
#          tasks:
           - name: Installing required packages
             yum:
               name: "{{ item }}"
               state: latest
             with_items:
               - httpd
               - syslinux
               - tftp-server
               - dnsmasq
               - pykickstart

